# Generated by scripts/sync_package_tooling.py — adjust MODULE paths if needed.
.PHONY: install install-dev test test-fast lint format type-check security clean build check help

install:
	pip install -e .

install-dev:
	pip install -e ".[dev]" 2>/dev/null || pip install -e .
	pip install -r requirements.txt
	pre-commit install || true

test:
	pytest tests/ -v --cov=fast_database --cov-report=term-missing || pytest -v

test-fast:
	pytest tests/ -v -x --tb=short -q || true

lint:
	ruff check src/fast_database src/fast_repositories tests || true

format:
	ruff format src/fast_database src/fast_repositories tests || true

type-check:
	mypy src/fast_database src/fast_repositories --ignore-missing-imports || true

security:
	bandit -r src/fast_database src/fast_repositories -q || true

clean:
	rm -rf build dist *.egg-info .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage coverage.xml
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

build: clean
	python -m build

check:
	twine check dist/*

help:
	@echo "Targets: install install-dev test lint format type-check security clean build"
